---

elasticsearch:
  hosts:
    - "elasticsearch-master"
  port: 9200
  security:
    enabled: true
    elasticsearchPassword: "<PUT_PASSWORD_HERE>"
  tls:
    enabled: true  # Required because ES uses HTTPS

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
