#
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes
# on push to the main branch.
# For real use you might want to restrict this to the "prod" branch.
#
---

name: Deploy mock-storage

on:
  #
  # Deploys the microservice on push to the specified subdirectory
  # in the main branch of this code repository.
  #
  push:
    branches:
      - main
    paths:
      - mock-storage/**

  #
  # Allows deployment to be invoked manually through the
  # GitHub Actions user interface.
  #
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      LOCAL_DEPLOY: ${{ secrets.LOCAL_DEPLOY  }}
      NAME: mock-storage
      DIRECTORY: mock-storage
      KUBECTL_VERSION: "v1.34.1"

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Builds the Docker image.
      #
      - name: Build
        run: ./scripts/cd/build-image.sh

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run: ./scripts/cd/push-image.sh

      # Installs Kubectl and connects it to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        if: ${{ env.LOCAL_DEPLOY == 'false' }}
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: ${{ env.KUBECTL_VERSION }}
      #
      # Install kubectl (works in GitHub Actions AND act)
      #
      - name: Install kubectl
        if: ${{ env.LOCAL_DEPLOY == 'true' }}
        run: |
          echo "Installing kubectl $KUBECTL_VERSION"
          curl -L -o kubectl "https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Setup kubeconfig
        if: ${{ env.LOCAL_DEPLOY == 'true' }}
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      #
      # Expands the configuration template and deploys the microservice.
      #
      - name: Deploy
        run: ./scripts/cd/deploy.sh

      #
      # (Optional) Debug cluster
      #
      - name: Test Kubernetes cluster access
        run: |
          kubectl get pods
          kubectl get deploy
          kubectl get services
